export const APP_CONST = {
  BASE_URL: 'https://api.openweathermap.org/data/2.5/',
  APP_ID: 'a889730a4fcf48a4c49ddcf9b2326446',
  ERR_NOTI: 'error'
};

export const ACTION = {
  FETCH_CURRENT_FORECAST: 'FETCH_CURRENT_FORECAST',
  HANDLE_CURRENT_FORECAST: 'HANDLE_CURRENT_FORECAST',
  FETCH_MULTI_CURRENT_FORECAST: 'FETCH_MULTI_CURRENT_FORECAST',
  HANDLE_MULTI_CURRENT_FORECAST: 'HANDLE_MULTI_CURRENT_FORECAST'
};

export const LINK = {
  MAIN: '/',
  DETAILS: '/compare'
};
